---
title: "4/25/2020 T-Tests"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: true
editor_options:
  chunk_output_type: console
---
<!-- author: "Julian McClellan" -->
<!-- date: "2/something/2020" -->
<!-- output:  -->
<!-- html_document: -->
<!-- toc: true -->

```{r setup, include=FALSE}
source("R/functions.R")
source("R/packages.R")
knitr::opts_chunk$set(echo = F, message = F, warning=F)
options(scipen=999) # No scientific notation
```

```{r define_groups}
# Data frame with combinations of freshman, treatment group, and seasons included
groupVarsDf <- list(freshVal = c(0, 1), 
                  treatVal = c(0, 1),
                  season = c("fall", "all")) %>%
  do.call(expand.grid, .)

# List of all the different data.frames of interest from the combinations above.
groupList <- groupVarsDf %>%
  pmap(.f = getTTestGroup)

# Group that discards non-compliant treatment from control
groupListDiscardNCT <- groupVarsDf %>%
  pmap(.f = getTTestGroup, nonComply = F)

indexKey <- data.table(sample1Index = 1:8,
                           sample2Index = 1:8,
                           indexName = c(
                                       # Fall12
                                       "nonfreshControlFall",
                                       "freshControlFall",
                                       "nonfreshTreatFall",
                                       "freshTreatFall",
                                       # Fall12 + Spring 13 
                                       "nonfreshControlAll",
                                       "freshControlAll",
                                       "nonfreshTreatAll",
                                       "freshTreatAll"))

# Please observe an abominable combination of dplyr and data.table

# DFs parameterizing calc2STTest function
fallParams <- list(sample1Index = 1:4,
                        sample2Index = 1:4) %>%
  do.call(expand.grid, .) %>%
  dplyr::filter(sample1Index < sample2Index) %>%
  as.data.table() %>%
  merge(indexKey[,.(sample1Index, index1Name = indexName)], by = c("sample1Index")) %>%
  merge(indexKey[,.(sample2Index, index2Name = indexName)], by = c("sample2Index")) %>%
  tidyr::crossing(outcomeVar = c("onlinechkdum", "purchased", "onlinechoicedum"))


allParams <- list(sample1Index = 5:8,
                        sample2Index = 5:8) %>%
  do.call(expand.grid, .) %>%
  dplyr::filter(sample1Index < sample2Index) %>%
  as.data.table() %>%
  merge(indexKey[,.(sample1Index, index1Name = indexName)], by = c("sample1Index")) %>%
  merge(indexKey[,.(sample2Index, index2Name = indexName)], by = c("sample2Index")) %>%
  tidyr::crossing(outcomeVar = c("onlinechkdum", "purchased", "onlinechoicedum"))

# Leave non-compliant treatment group in the control group (treatment == 0 and offered == 1)
fallTTestResults <- fallParams %>%
  purrr::pmap_df(.f = calc2STTest, groupList = groupList)

allTTestResults <- allParams %>%
  purrr::pmap_df(.f = calc2STTest, groupList = groupList)

# Discard non-compliant treatment group from the control group
fallTTestResultsDiscardNCT <- fallParams %>%
  purrr::pmap_df(.f = calc2STTest, groupList = groupListDiscardNCT)

allTTestResultsDiscardNCT <- allParams %>%
  purrr::pmap_df(.f = calc2STTest, groupList = groupListDiscardNCT)
```

## 2-Sample T-Tests

### Leaving in Non-compliant treatment group

```{r plot_ttest_results_with_nc_treatment}
library(ggplot2)
(ggplot(fallTTestResults, aes(x=group_compared, y=estimate)) +
  geom_bar(stat="identity", aes(fill = sig)) +
  geom_errorbar(aes(ymin=conf.low, ymax=conf.high),
                width=.2,                    # Width of the error bars
                ) +
  labs(title = "Welch 2-Sample T-Test Results | Fall12 Only", subtitle = "95% CI | Assume unequal variance") +
  facet_wrap(. ~ outcomeVar) +
  theme_minimal() +
  coord_flip() +
  scale_fill_manual(values = c("sig" = "tomato", "nonsig" = "grey")) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
)

(ggplot(allTTestResults, aes(x=group_compared, y=estimate)) +
  geom_bar(stat="identity", aes(fill = sig)) +
  geom_errorbar(aes(ymin=conf.low, ymax=conf.high),
                width=.2,                    # Width of the error bars
                ) +
  labs(title = "Welch 2-Sample T-Test Results | Fall12 + Spring13", subtitle = "95% CI | Assume unequal variance") +
  facet_wrap(. ~ outcomeVar) +
  theme_minimal() +
  coord_flip() +
  scale_fill_manual(values = c("sig" = "tomato", "nonsig" = "grey")) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
)
```

### Leaving *out* Non-compliant treatment group

```{r plot_ttest_results_wo_nc_treatment}
(ggplot(fallTTestResultsDiscardNCT, aes(x=group_compared, y=estimate)) +
  geom_bar(stat="identity", aes(fill = sig)) +
  geom_errorbar(aes(ymin=conf.low, ymax=conf.high),
                width=.2,                    # Width of the error bars
                ) +
  labs(title = "Welch 2-Sample T-Test Results | Fall12", subtitle = "95% CI | Assume unequal variance") +
  facet_wrap(. ~ outcomeVar) +
  theme_minimal() +
  coord_flip() +
  scale_fill_manual(values = c("sig" = "tomato", "nonsig" = "grey")) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
)

(ggplot(allTTestResultsDiscardNCT, aes(x=group_compared, y=estimate)) +
  geom_bar(stat="identity", aes(fill = sig)) +
  geom_errorbar(aes(ymin=conf.low, ymax=conf.high),
                width=.2,                    # Width of the error bars
                ) +
  labs(title = "Welch 2-Sample T-Test Results | Fall12 + Spring13", subtitle = "95% CI | Assume unequal variance") +
  facet_wrap(. ~ outcomeVar) +
  theme_minimal() +
  coord_flip() +
  scale_fill_manual(values = c("sig" = "tomato", "nonsig" = "grey")) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
)
```

## Means tests

```{r get_means_tests_params_and_results}
# Get means with .95 conf intervals of certain outcome vars for fall12 with the
# new control group specification (discard non-compliant treatment)
fallMeansParams <- list(sample1Index = 1:4,
                        outcomeVar = c("onlinechkdum", "purchased", "onlinechoicedum")
                        ) %>%
  do.call(expand.grid, .) %>%
  inner_join(indexKey %>% select(-sample2Index)) %>%
  rename(index1Name = indexName) %>%
  mutate(outcomeVar = as.character(outcomeVar))

fallMeansResults <- fallMeansParams %>%
  purrr::pmap_df(.f = calc1STTest, groupList = groupListDiscardNCT)

(ggplot(fallMeansResults, aes(x=group, y=estimate)) +
  geom_bar(stat="identity", aes(fill = sig)) +
  geom_errorbar(aes(ymin=conf.low, ymax=conf.high),
                width=.2,                    # Width of the error bars
                ) +
  labs(title = "Welch 1-Sample T-Test Results | Fall12", subtitle = "95% CI") +
  facet_wrap(. ~ outcomeVar) +
  theme_minimal() +
  coord_flip() +
  scale_fill_manual(values = c("sig" = "tomato", "nonsig" = "grey")) +
  geom_hline(yintercept = .5, linetype = "dotted") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
)
```

